### ISSUE TITLE
Problems while installing

### ISSUE THREAD

**Issue by ghost** [tintoy/nuget-client-nodejs#1]
Can u please define all necessary dependencies for this package? Why did you publish this? Package is not installing out of the box.

**Comment by tintoy** [comment]
Hi - sorry it's causing problems for you. It's been a while since I've worked on this so I honestly can't remember at the moment :)

Let me have a quick look at it and get back to you.

**Comment by tintoy** [comment]
Hi - I just fetched the source for this myself and ran `npm install` (Node v9.x on Windows 10 and Ubuntu 16.04) and no errors were reported; what error are you seeing when you install it?

**Comment by tintoy** [comment]
> Why did you publish this?

This package was originally used by a [VS Code extension](https://github.com/tintoy/msbuild-project-tools-vscode) which has since then switched to using a language server written on a platform other than NodeJS.

**Comment by ghost** [comment]
Hi again. I created a new project for testing, and tried to install this package via npm. Result: 
![image](https://user-images.githubusercontent.com/7829653/40279327-4c187f00-5c49-11e8-84ad-548b61786b02.png)

So, the typescript dependency is missing.
After installing typescript i catch this:

![image](https://user-images.githubusercontent.com/7829653/40279343-8c816d5e-5c49-11e8-8d6a-ae125267fc37.png)

So, i think u need to fix your package.json file

**Comment by tintoy** [comment]
Oops! I realise now I missed that error because have Typescript installed globally. I'll sort that out this morning; sorry for the inconvenience 😊

**Comment by tintoy** [comment]
Hmm, looking at package.json, it seems like I may have fixed this a while back but forgot to publish a new version of the package. Should be easy enough to test.

**Comment by ghost** [comment]
Okay, I will test new version ☺️

**Comment by tintoy** [comment]
Might be an hour or 2 - it's 4:30am here and my laptop's in the car. Will
publish ASAP.

**Comment by tintoy** [comment]
Ugh, no turns out the problem is the `install` script - shouldn't be compiling on install. I'll sort it out in an hour or so...

**Comment by tintoy** [comment]
Hi - could you try [nuget-client@0.1.6](https://www.npmjs.com/package/nuget-client/v/0.1.6)? I tested it and a clean install seems to work correctly, but I'd appreciate a second opinion ;-)

**Comment by ghost** [comment]
Works perfectly 👍  thanks alot for quick fixing
